version: "3"
services:
  web:
    build:
      context: .
      target: "develop-stage"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  cargo-cache:
  target-cache:
